version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:8.0
    container_name: checkpoint_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: checkpoint_order_processing
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - checkpoint_network

  # Node.js Application
  app:
    build: .
    container_name: checkpoint_app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/checkpoint_order_processing?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - checkpoint_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      timeout: 10s
      retries: 3
      start_period: 30s
      interval: 30s

volumes:
  mongodb_data:

networks:
  checkpoint_network:
    driver: bridge